### ISSUE TITLE
關懷機器人功能計畫

### ISSUE THREAD

**Issue by nnricn** [microseyuiyuu/Anime-Club-main#11]
打算唯夕提議的關懷功能開發計畫納入考量
這樣等開發功能時候提醒潛水七天至十四天
給予公共頻道艾特方式提醒用戶出來說話。

**Comment by microseyuiyuu** [comment]
Wrong place
Please move this issue to Anime-Club-bot repo

issue 的位置开错了
需要开在 Anime-Club-bot repo 这个仓库
